Repository Arquisoft/wichat_es2a, pull requests merged in 2025-03, with the labels that each got.

#40 Modifications in Documentation 1 after teacher review
  docs/src/01_introduction_and_goals.adoc
Labels: documentation

#44 Modifications in Documentation 5 after teacher review
  docs/images/Building_Block_View.png
  docs/images/Building_Block_View.svg
  docs/src/05_building_block_view.adoc
Labels: documentation

#43 Modifications in Documentation 2 after teacher review
  docs/src/02_architecture_constraints.adoc
Labels: documentation

#47 Documentation #9 - Architecture Decisions (Update)
  docs/images/neobrutalism.png
  docs/src/09_architecture_decisions.adoc
Labels: documentation

#60 Gemini ADR added.
  docs/images/gemini.png
  docs/src/09_architecture_decisions.adoc
Labels: documentation

#67 Basic functionality of wikidata
  docker-compose.yml
  wikidata/Dockerfile
  wikidata/api.js
  wikidata/model/wikidataModel.js
  wikidata/package-lock.json
  wikidata/package.json
  wikidata/repositories/wikidataRepository.js
  wikidata/server.js
  wikidata/services/wikidataService.js
  wikidata/tests/api.test.js
  wikidata/tests/wikidataService.test.js
Labels: backend, test, wikidata

#79 Development FrontEnd service
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.js
  webapp/src/App.jsx
  webapp/src/Game.jsx
  webapp/src/components/ChatPanel.jsx
  webapp/src/components/GamePanel.jsx
  webapp/src/components/Nav.jsx
  webapp/src/components/config/default-Theme.json
  webapp/src/components/context/AuthContext.jsx
  webapp/src/components/context/ConfigContext.jsx
  webapp/src/components/context/LocaleContext.jsx
  webapp/src/media/logoS.svg
  webapp/src/media/logoWiChat.svg
  webapp/src/media/madrid_mobile.webp
  wikidata/package-lock.json
  wikidata/package.json
  wikidata/server.js
  wikidata/wikidataService.js
Labels: frontend

#78 Development llm service
  .github/workflows/build.yml
  .gitignore
  docker-compose.yml
  docs/package-lock.json
  docs/package.json
  gatewayservice/package-lock.json
  gatewayservice/package.json
  llmservice/conversation-model.js
  llmservice/conversation-model.test.js
  llmservice/llm-service.js
  llmservice/llm-service.test.js
  llmservice/package-lock.json
  llmservice/package.json
  users/authservice/package-lock.json
  users/authservice/package.json
  users/userservice/package-lock.json
  users/userservice/package.json
  webapp/package-lock.json
  webapp/package.json
  wikidata/package-lock.json
  wikidata/package.json
Labels: backend

#87 Improved and fixed the wikidata backend
  docker-compose.yml
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/GamePanel.jsx
  wikidata/.dockerignore
  wikidata/Dockerfile
  wikidata/api.js
  wikidata/package-lock.json
  wikidata/package.json
  wikidata/repositories/wikidataRepository.js
  wikidata/server.js
  wikidata/src/model/wikidataFakeAnswers.js
  wikidata/src/model/wikidataModel.js
  wikidata/src/model/wikidataQueries.js
  wikidata/src/repositories/wikidataRepository.js
  wikidata/src/services/wikidataFakeAnswersService.js
  wikidata/src/services/wikidataService.js
  wikidata/src/wikidataRoutes.js
  wikidata/tests/api.test.js
  wikidata/tests/wikidataFakeAnswers.test.js
  wikidata/tests/wikidataRepository.test.js
  wikidata/tests/wikidataService.test.js
  wikidata/wikidataService.js
Labels: backend, test, wikidata

#91 Enhance Home page, Login flow, and Add User functionality with custom theme and user validation
  users/authservice/auth-service.js
  users/userservice/deleteUsers.js
  users/userservice/user-service.js
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.jsx
  webapp/src/components/AddUser.js
  webapp/src/components/GamePanel.jsx
  webapp/src/components/Home.jsx
  webapp/src/components/Login.js
  webapp/src/components/Nav.jsx
  webapp/src/components/ProtectedRoute.jsx
  webapp/src/media/login.svg
Labels: backend, frontend

#96 Wikidata in Gateway Service and more
  gatewayservice/gateway-service.js
  gatewayservice/package-lock.json
  llmservice/package-lock.json
  users/authservice/package-lock.json
  users/userservice/package-lock.json
  webapp/src/components/GamePanel.jsx
  wikidata/src/model/wikidataFakeAnswers.js
  wikidata/src/model/wikidataQueries.js
  wikidata/src/services/wikidataFakeAnswersService.js
  wikidata/src/services/wikidataService.js
  wikidata/src/wikidataRoutes.js
Labels: bug, backend, frontend, wikidata

#102 Fix docker and added file to run application
  docker-compose.yml
  start.bat
Labels: bug, fix

#103 Add Profile & Contact Pages with Theme Integration & UX Fixes & Countdown component
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.jsx
  webapp/src/components/Contact.jsx
  webapp/src/components/Countdown.css
  webapp/src/components/Countdown.jsx
  webapp/src/components/Nav.jsx
  webapp/src/components/Profile.jsx
  webapp/src/components/config/default-Theme.json
  webapp/src/media/men.jpg
  webapp/src/media/women.jpg
Labels: enhancement, frontend
